### ISSUE TITLE
Util.getOrCreateCell Error

### ISSUE THREAD

**Issue by hagyeongkim** [SheetJS/jxls#3]
version : jxls-core-1.0.6

An error occurs when I try to download Excel with a **formula**.
cause in Util.getOrCreateCell > Row.CREATE_NULL_AS_BLANK

This should be fixed this way.
Row.MissingCellPolicy.CREATE_NULL_AS_BLANK

**Comment by reviewher** [comment]
The official repo is on sourceforge at http://jxls.sourceforge.net -- this is a small github mirror created to simplify the [`test_files` project](https://github.com/SheetJS/test_files).  Raise this issue with the official project
